[book]
authors = ["Nathan Douglas"]
language = "en"
multilingual = false
src = "src"
title = "Hornvale"
description = "A companion book for Hornvale."
create-missing = false

[output.html]
mathjax-support = true
site-url = "/book/"
git-repository-url = "https://github.com/hornvale/book.git"
git-repository-icon = "fa-github"
